# Generated by Django 3.2.4 on 2021-06-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recurso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
    ]
