# Generated by Django 3.2.4 on 2021-06-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(max_length=500, verbose_name='Comentário'),
        ),
    ]
